sudo: false
language: python
python:
  - "2.7"
  - "3.6"
install: pip install tox-travis
script: tox
before_deploy: tox -e bdist
deploy:
  provider: releases
  api_key:
    secure: ipiRklWb6Em4Mi/33osX0BPTR468uG+lrwQAm1nCJq8oWgtJx4EWaJ5eRLyG8ZzRTc7tGmEwOiDHY4hZrhxNCeAatzTi0zDGgy/iVrymZNIEgZK/Jd2ufNRnmCfMFm8ZorRpKH7mtGMb7h5GnV9kpAHJL/XkHPW84uv4ivn24d/GpCixbji///jL9mCWhnGj1cIz3NbP2+mDWQKnupL/VHVSV+sn31nwX4WSpxjJ55LQ0dM4K2C7O52h4FpS5H4Gy5+DVmd8ZX64AVS1gquOtTUoxme1WCFxer9vNrbfbeV0plxqRPSfXPWtsj3kifMwtJrkgyWe/x1nP+Bedsx1E3stgOqjsqdR9gVLnp0BlsPE+QulmqMP1iJcoxwC0x/LGvJbzTICx2kx/EeVRqFFwvQFIx2OVr6r+M2xZCBWqYN59oSt1NYVNz3cy7yYOyPDMFBiR1vwW281FvUkuunVthwY0f+5V9D2ktDHxBdMA3lfo9+cCSs/wF5/qSvNeepJI4pd2D+S9GWAl1a8+i4zyBYkyDTt4eftm72rhDVhiLjjLXRoZzFH1IQfZsMrFrLcF7PhLz8Cy0B5caXtR3vXQtbexxwj9CNjxP38EKlBmo4BL2isr5zYUJlB9MD3rMO3J+s0iTF+PRWjiQ1xR6iTrIs5tHvk4vPYcmdI0xGZEhc=
  skip_cleanup: true
  file_glob: true
  file: "dist/*"
  on:
    repo: daltonmaag/vttLib
    tags: true
    all_branches: true
    python: 3.6
